# Generated by Django 2.1 on 2019-11-03 21:16

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('poster_url', models.URLField(max_length=250)),
                ('broadcasting_start_time', models.TimeField()),
                ('broadcasting_end_time', models.TimeField()),
                ('broadcasting_station', models.CharField(max_length=20)),
                ('is_broadcasting', models.BooleanField(default=True)),
                ('episode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='TaggedBroadCastingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.Drama')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_taggedbroadcastingday_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.Drama')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_taggedgenre_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drama',
            name='broadcasting_day',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='broadcasting_day', through='drama.TaggedBroadCastingDay', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='drama',
            name='genre',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='genre', through='drama.TaggedGenre', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
